# Generated by Django 4.1.7 on 2023-03-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
