# Generated by Django 4.1.7 on 2023-03-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0022_alter_artist_id'),
        ('user_account', '0002_remove_account_first_name_remove_account_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.AddField(
            model_name='account',
            name='favorite_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.artist'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
