# Generated by Django 4.1.7 on 2023-03-05 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0022_alter_artist_id'),
        ('user_account', '0003_remove_account_email_account_favorite_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, null=True)),
                ('biography', models.TextField(null=True)),
                ('favorite_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.artist')),
            ],
        ),
    ]
