# Generated by Django 4.1.7 on 2023-03-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_remove_favorite_account_favorite_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'artwork'), name='unique_user_artwork_combination'),
        ),
    ]
