# Generated by Django 4.1.7 on 2023-03-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_favorite_unique_user_artwork_combination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
