# Generated by Django 4.1.7 on 2023-03-15 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_account', '0005_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.EmailField(default='admin@localhost', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_email_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
