# Generated by Django 4.1.7 on 2023-03-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_request_email_alter_request_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
