# Generated by Django 4.1.7 on 2023-03-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='images/users/default/unknown.jpg', max_length=256, upload_to='images/users/'),
        ),
    ]
