# Generated by Django 4.1.7 on 2023-03-06 22:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='test', upload_to=users.models.upload_to),
            preserve_default=False,
        ),
    ]
