# Generated by Django 4.1.7 on 2023-03-07 08:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='/default/unknown.png', upload_to=users.models.upload_to),
        ),
    ]
