# Generated by Django 4.1.7 on 2023-03-12 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0024_remove_artwork_users'),
        ('users', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_artist',
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='artworks',
            field=models.ManyToManyField(blank=True, related_name='favorites_artworks', through='users.Bookmark', to='artwork.artwork'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'artwork'), name='unique_user_artwork_combination_bookmark'),
        ),
    ]
