# Generated by Django 4.1.7 on 2023-03-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_favorite_artist_bookmark_user_artworks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='artworks',
            new_name='bookmarked_artworks',
        ),
    ]
