# Generated by Django 4.1.7 on 2023-03-07 09:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='images/users/default/unknown.jpg', upload_to=users.models.upload_to),
        ),
    ]
