# Generated by Django 4.1.7 on 2023-03-12 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0024_remove_artwork_users'),
        ('users', '0006_rename_artworks_user_bookmarked_artworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.artist'),
        ),
    ]
