# Generated by Django 4.1.7 on 2023-03-15 21:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_favorite_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='images/users/default/unknown.jpg', max_length=256, upload_to=users.models.upload_to_user),
        ),
    ]
