# Generated by Django 4.1.5 on 2023-01-23 16:42

import artwork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=80, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=artwork.models.upload_to)),
            ],
        ),
    ]
