# Generated by Django 4.1.7 on 2023-02-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('years', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('wikipedia', models.CharField(max_length=64)),
                ('paintings', models.IntegerField()),
            ],
        ),
    ]
