# Generated by Django 4.1.7 on 2023-02-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='genre',
            new_name='base',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='paintings',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='wikipedia',
        ),
        migrations.AddField(
            model_name='artist',
            name='period',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='school',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(db_column='artist', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='years',
            field=models.CharField(db_column='born-died', max_length=50),
        ),
    ]
