# Generated by Django 4.1.5 on 2023-02-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_rename_genre_artist_base_remove_artist_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='sourcePage',
            field=models.CharField(db_column='url', default='test', max_length=64),
            preserve_default=False,
        ),
    ]
