# Generated by Django 4.1.7 on 2023-02-21 13:13

import artwork.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_artist_sourcepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='author',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='description',
        ),
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='artwork.artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='file_info',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='picture_data',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='id',
            field=models.IntegerField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image_url',
            field=models.ImageField(db_column='jpg url', default='test', max_length=50, upload_to=artwork.models.upload_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
