# Generated by Django 4.1.7 on 2023-02-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0008_alter_artwork_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
