# Generated by Django 4.1.7 on 2023-02-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0009_alter_artwork_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='file_info',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='picture_data',
        ),
        migrations.AddField(
            model_name='artwork',
            name='color',
            field=models.CharField(default='test', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='file_dimension',
            field=models.CharField(default='test', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='resolution',
            field=models.CharField(default='test', max_length=24),
            preserve_default=False,
        ),
    ]
