# Generated by Django 4.1.7 on 2023-02-24 23:40

import artwork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0010_remove_artwork_file_info_remove_artwork_picture_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='base',
            new_name='profession',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='period',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='sourcePage',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='years',
        ),
        migrations.AddField(
            model_name='artist',
            name='biography',
            field=models.TextField(db_column='description', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='birth_data',
            field=models.CharField(db_column='birth data', default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='portrait',
            field=models.ImageField(default='test', max_length=50, upload_to=artwork.models.upload_to),
            preserve_default=False,
        ),
    ]
