# Generated by Django 4.1.7 on 2023-02-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0011_rename_base_artist_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
    ]
