# Generated by Django 4.1.7 on 2023-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0017_alter_artwork_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(db_column='artist', max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='id',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
