# Generated by Django 4.1.7 on 2023-02-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0018_artist_id_alter_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='author_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='artwork.artist'),
            preserve_default=False,
        ),
    ]
