# Generated by Django 4.1.7 on 2023-02-28 12:46

import artwork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0020_alter_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='portrait',
            field=models.ImageField(max_length=64, upload_to=artwork.models.upload_to_artist),
        ),
    ]
