# Generated by Django 4.1.7 on 2023-02-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0021_alter_artist_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
