# Generated by Django 4.1.7 on 2023-03-12 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0022_alter_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='favorites_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
