# Generated by Django 4.1.7 on 2023-03-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0023_artwork_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='users',
        ),
    ]
